### ISSUE TITLE
[Feature Request] UDPGW

### ISSUE THREAD

**Issue by tormentous** [heiher/hev-socks5-tunnel#184]
UDP Gateway (UDPGW) is a daemon that enables UDP packet forwarding over SSH tunnels. It's particularly useful for applications that rely on UDP, such as DNS, VoIP, and online gaming, when you need to route their traffic through an SSH tunnel.
How it works:
 * UDP Packet Arrival: A UDP packet arrives at the client machine.
 * UDPGW Intercept: The UDPGW daemon intercepts the packet.
 * Packet Encapsulation: The packet is encapsulated within an SSH packet.
 * SSH Tunnel Transmission: The encapsulated packet is sent through the SSH tunnel.
 * Server-Side Decapsulation: On the server side, the UDPGW daemon receives the SSH packet and decapsulates the original UDP packet.
 * UDP Packet Forwarding: The original UDP packet is forwarded to its intended destination.
Key Benefits:
 * Enhanced Privacy: By encrypting UDP traffic within an SSH tunnel, you can increase privacy and security.
 * Circumventing Network Restrictions: UDPGW can help bypass network restrictions or firewalls that block UDP traffic.
 * Improved Reliability: SSH tunnels provide a more reliable connection than direct UDP connections, especially in unstable network environments.
Common Use Cases:
 * Secure DNS: Encrypts DNS queries and responses for added privacy.
 * VoIP Over SSH: Enables secure VoIP calls over SSH tunnels.
 * Online Gaming: Allows online gaming through firewalls or restricted networks.
 * Custom Applications: Can be used with any application that relies on UDP.
Popular Implementations:
 * BadVPN: A popular open-source tool that includes UDPGW functionality.
 * Other VPN Clients: Some VPN clients may offer built-in UDPGW capabilities.
By understanding UDPGW and its applications, you can leverage its power to enhance your network security and flexibility.

**Comment by heiher** [comment]
If the UDPGW requires running a daemon on the SSH server, I recommend replacing it with `hev-socks5-server`. You can then map the server-side [`hev-socks5-server`](https://github.com/heiher/hev-socks5-server) to your local host via SSH's TCP port forwarding. This setup allows `hev-socks5-tunnel` to relay [UDP over TCP](https://github.com/heiher/hev-socks5-tunnel/blob/master/conf/main.yml#L24-L25) through the SSH tunnel.

**Comment by tormentous** [comment]
> If the UDPGW requires running a daemon on the SSH server, I recommend replacing it with `hev-socks5-server`. You can then map the server-side [`hev-socks5-server`](https://github.com/heiher/hev-socks5-server) to your local host via SSH's TCP port forwarding. This setup allows `hev-socks5-tunnel` to relay [UDP over TCP](https://github.com/heiher/hev-socks5-tunnel/blob/master/conf/main.yml#L24-L25) through the SSH tunnel.

there are a lot of server providers that offers udpgw, but i think they use badvpn tun2socks. Implementing that to hev-socks5-tunnel would be benificial. thank you!

e.g: https://lionssh.com/services/ssh/asia/IN/30-days

**Comment by HeXis-YS** [comment]
@tormentous 
What is the point of implementing udpgw? It does not offer any significant performance or security benefits.
AFAIK, udpgw was introduced by badvpn in 2011, and has not been updated since 2013. As of 2021, the entire badvpn program is no longer maintained.
Compatibility with this feature, which is already (almost) not used by anyone, is an additional burden for developers.
People will use Windows 7 or even Windows XP for an old but important feature or software. Not to mention, badvpn-tun2socks works well on modern OSes and you don't even need to make any sacrifices. If you think udpgw is important, please use badvpn-tun2socks, which offers similar or even more features and functions than hev-socks5-tunnel.
Also, maybe you could try some more advanced solutions instead of sticking with something that's over a decade old.

**Comment by tormentous** [comment]
> @tormentous What is the point of implementing udpgw? It does not offer any significant performance or security benefits. AFAIK, udpgw was introduced by badvpn in 2011, and has not been updated since 2013. As of 2021, the entire badvpn program is no longer maintained. Compatibility with this feature, which is already (almost) not used by anyone, is an additional burden for developers. People will use Windows 7 or even Windows XP for an old but important feature or software. Not to mention, badvpn-tun2socks works well on modern OSes and you don't even need to make any sacrifices. If you think udpgw is important, please use badvpn-tun2socks, which offers similar or even more features and functions than hev-socks5-tunnel. Also, maybe you could try some more advanced solutions instead of sticking with something that's over a decade old.

Simple. because this performs faster as the authors comparision to badvpn but it lacks such feature mentioned.

**Comment by HeXis-YS** [comment]
@tormentous 
How fast do you need?
badvpn-tun2socks can serve 2-4Gbps of traffic, which is sufficient in most cases. If you think that's not enough, tweak `lwipopts.h` and recompile it. If that's still not enough, then try other options. V2Ray, Xray, sing-box, whatever.
You'd rather have ChatGPT write this issue than use it to solve the problem. You didn't even check what ChatGPT worte at all. Are you serious when you want to do online gaming and VoIP over SSH tunnels, and you still care about performance?
Please stop asking developers to implement certain features just because **YOU** need them.
